name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci_lint_workflow:
    uses: pluralsh/steampipe-workflows/.github/workflows/golangci-lint.yml@b76001ea63275b69b80368fb948bb629fabaf8f2
    with:
      timeout: 10m