name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci_lint_workflow:
    uses: pluralsh/steampipe-workflows/.github/workflows/golangci-lint.yml@ad5dcdb68fc6a8c0bf19667640f0ed9316316f93
    with:
      timeout: 10m