name: Release Steampipe Anywhere Components

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        description: "The version to release (must be prefixed with 'v')"
        required: true
        
permissions:
  contents: write

jobs:
  anywhere_publish_workflow:
    uses: pluralsh/steampipe-workflows/.github/workflows/steampipe-anywhere.yml@fd95e5f78a2f5611bb8c451f810b1c7dee3fa578
