name: Release Steampipe Anywhere Components

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        description: "The version to release (must be prefixed with 'v')"
        required: true
        
permissions:
  contents: write

jobs:
  anywhere_publish_workflow:
    uses: pluralsh/steampipe-workflows/.github/workflows/steampipe-anywhere.yml@ad5dcdb68fc6a8c0bf19667640f0ed9316316f93
