name: Release Steampipe Anywhere Components

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        description: "The version to release (must be prefixed with 'v')"
        required: true
        
permissions:
  contents: write

jobs:
  anywhere_publish_workflow:
    uses: pluralsh/steampipe-workflows/.github/workflows/steampipe-anywhere.yml@c4ad5ad015d52a5ab955d5f3b2949422a926e06c
